apiVersion: v1
kind: ReplicationController
metadata:
  name: test-fs
  namespace: rook
  labels:
    k8s-app: kube-registry
    version: v0
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 3
  selector:
    k8s-app: test-fs
    version: v0
  template:
    metadata:
      labels:
        k8s-app: test-fs
        version: v0
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: test
        image: ubuntu:latest
        command:
          - tail
          - -f
          - /dev/null
        volumeMounts:
        - name: image-store
          mountPath: /var/lib/registry
      volumes:
      - name: image-store
        flexVolume:
          driver: rook.io/rook
          fsType: ceph
          options:
            fsName: shared-fs # name of the filesystem specified in the filesystem CRD.
            clusterName: rook # namespace where the Rook cluster is deployed
            # by default the path is /, but you can override and mount a specific path of the filesystem by using the path attribute
            # path: /some/path/inside/cephfs