apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  labels:
    app: kubeflow-pipelines
    instance: kfp-standalone-1
  name: vm-viewer
  namespace: kfp-ci
spec:
  member: serviceAccount:kfp-standalone-1-vm@kfp-ci.iam.gserviceaccount.com
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    external: projects/kfp-ci
    kind: Project
  role: roles/viewer
