apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: ci-team-v3
  namespace: kfp-ci
spec:
  member: group:ci-team@kubeflow.org
  role: roles/owner
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: projects/kfp-ci
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: prow-test-sa-v2
  namespace: kfp-ci
spec:
  member: serviceAccount:kf-ci-v1-prow@kubeflow-ci.iam.gserviceaccount.com
  # Refer to the following documentation for required permission to access KFP:
  # https://cloud.google.com/ai-platform/pipelines/docs/access-control#grant_a_user_access_to
  role: roles/iam.serviceAccountUser
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    name: kfp-standalone-1-vm # {"$kpt-set":"name-sa"}
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: prow-test-sa-gcs-object-admin-v3
  namespace: kfp-ci
spec:
  member: serviceAccount:kf-ci-v1-prow@kubeflow-ci.iam.gserviceaccount.com
  role: roles/storage.objectAdmin
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: projects/kfp-ci
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: kfp-standalone-1-vm
  namespace: kfp-ci
spec:
  member: serviceAccount:kfp-standalone-1-vm@kfp-ci.iam.gserviceaccount.com
  # Refer to the following documentation for required permission to access KFP:
  # https://cloud.google.com/ai-platform/pipelines/docs/access-control#grant_a_user_access_to
  # Even the vm service account itself needs serviceAccountUser role.
  role: roles/iam.serviceAccountUser
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    name: kfp-standalone-1-vm # {"$kpt-set":"name-sa"}
